# UserConfig
FilePath: example.srt
# 動画サイズ [横幅, 縦幅]
MovieSize: [1280, 720]
FrameRate: 30
AudioRate: 44100
AudioCh: 2
Layer: 5

# ObjConfig
# テキストの配置
X: 0.0
Y: 350.0
Z: 0.0

# 拡大率
Zoom: 100.00
# 透明度
AlphaBlend: 0.0
# 回転
Rotate: 0.0
# サイズ
Size: 100
# 合成モード 0 ~ 13
Blend: 0

# TextConfig
# フォント
Font: メイリオ

# 太字 0 or 1
Bold: 0
# 斜字 0 or 1
Italic: 0
# 文字の縁取り、影の設定 0 ~ 6
EffectType: 3
# 長さの自動調節 0 or 1
AutoAdjust: 0
# 滑らかにする 0 or 1
Soft: 0
# 等間隔モード 0 or 1
Monospace: 0
# テキストのそろえ方 0 ~ 17
Align: 7
# 字間
SpacingX: 0
# 行間
SpacingY: 0
# 高精度モード 0 or 1
Precision: 0
# テキストの色
Color: "0000ff"
# テキストの縁、影の色
Color2: "ffffff"
