# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master"]
    types:    closed

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["386", "amd64", "arm"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: set module
      run:  go mod tidy

    - name: Set config.yaml
      run:  cp config.sample.yaml config.yaml

    - name: Build
      run:  GOOS=windows GOARCH=${{ matrix.arch }} go build -ldflags="-s -w" -trimpath . -o SRTtoEXO-${{ matrix.arch }}.exe

    - name: Upload .exe file
      uses: actions/upload-artifact@v4
      with:
        name: exe_file
        path: SRTtoEXO-${{ matrix.arch }}.exe

    - name: Upload config file
      uses: actions/upload-artifact@v4
      with:
        name: exe_file
        path: config.yaml


    - name: Test
      run: go test -json > TestResults-${{ matrix.arch }}.json
    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results-${{ matrix.arch }}
        path: TestResults-${{ matrix.arch }}.json

  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["386", "amd64", "arm"]

    steps:
      - name: Download .exe file
        uses: actions/download-artifact@v4
        with:
          name: exe_file

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: GITHUB_TOKEN
          automatic_release_tag: "latest"
          prerelease: false
          title: "Development Auto Build"
          files: |
            SRTtoEXE-*.exe
            config.yaml
            README.txt
            LICENSE

